version: '3.8'

services:
  frontend:
    build: .
    container_name: logishift_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - main_net

networks:
  main_net:
    external: true
    name: smenabot-net
