version: '3.8'

services:
  frontend:
    build: .
    container_name: logishift_frontend
    restart: always
    ports:
      - "8080:80" 
      # Сайт будет доступен на порту 8080. 
      # Внутри контейнера Nginx слушает 80, мы пробрасываем его наружу.